blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls'))
]

blog/blog_app/urls.py
from django.urls import path
from django.urls import include
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('create_page/', views.createPage, name='create_page'),
    path('remove/<int:page_id>/', views.removePage, name='remove_page'),
    path('read/<int:page_id>/', views.readPage, name='read_page'),
    path('update_page/', views.updatPage, name='update_page'),
]

blog/blog_app/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    content = models.CharField(max_length=2000)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=100, default="none")
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.utils import timezone
from . import models
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

# class IndexView(generic.ListView):
    # template_name = 'index.html'
    # context_object_name = 'pages'

    # def get_queryset(self):
        # return models.Page.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]

def indexView(request):
    model = models.Page
    pages = model.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]
    lastconection = 0;
    if(len(pages) > 0):
        lastconection = pages[0].pub_date
    else:
        lastconection = timezone.now()
    return render(request, 'index.html', context={'pages':pages, 'last_connection':lastconection})

def createPage(request):
    model = models.Page
    description = request.POST['content'][:20] + "..."
    page = model(title = request.POST['title'], content = request.POST['content'], pub_date = timezone.now(), description=description)
    page.save()
    return HttpResponseRedirect(reverse('blog_app:index'))


def readPage(request, page_id):
    model = models.Page
    page = get_object_or_404(model, pk=page_id)
    return render(request, 'page.html', context={'page': page})

def updatPage(request):
    model = models.Page
    page = get_object_or_404(model, pk=request.POST['page_id'])
    page.content = request.POST['content']
    page.title = request.POST['title']
    page.pub_date = timezone.now()
    page.save()
    return HttpResponseRedirect(reverse('blog_app:index'))


def removePage(request, page_id):
    model = models.Page
    page = get_object_or_404(model, pk=page_id)
    page.delete()
    return HttpResponseRedirect(reverse('blog_app:index'))

blog/blog_app/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Sapiens</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Old+Uyghur&family=Oswald:wght@200&display=swap" rel="stylesheet">
	<link rel="icon" type="image/x-icon" href="{% static 'img/monkey.ico' %}">
	<link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>
<body>
		<div id="container">
				<header>
						<div id="header-bg"></div>
						<img src="{%static "img/profile-photo.jpeg"%}" alt="profile-photo" id="profile-photo">
						<div id="profile-title-section">
								<h3>Sapiens</h3>
								<p>Last connection: <b>{{last_connection}}</b></p>
						</div>
				</header>	
				<section id="options-nav">
						<ul>
								<li><a href="#">Author</a></li>
								<li><a href="#">All pages</a></li>
						</ul>
				</section>

				<section id="pages-container">
						<div id="reading-pages-container">
								<h3>Last 1-5 pages:</h3><br><br>

								{% for el in pages %}
								<div class="page">
										<div class="page-title">
												<p>{{el.title}}</p>
												<div>
														<form action="{% url 'blog_app:read_page' el.id %}"><button class="go-page-btn">Go</button></form>
														<form action="{% url 'blog_app:remove_page' el.id %}"><button class="remove-page-btn">Remove</button></form>
												</div>
										</div>
										<p class="page-description">{{el.description}}</p>
								</div>
								{% endfor %}

						</div>	

						<div id="writing-pages-container">
								<h3>Add page:</h3><br></br>
								<form id="create_page_form" autocomplete='off' action="{% url 'blog_app:create_page' %}" method="POST">
										{% csrf_token %}
										<label for="title">Title: </label><br>
										<input id="title" required name="title" placeholder="..."></input><br>

										<label for="content">Content: </label><br>
										<textarea id="content" required name="content"></textarea>
										
										<button id="discard-btn">Discard page</button>
										<button id="submit-btn">Publish page</button>
								</form>
						</div>
				</section>
		</div>
</body>
<script src="{% static 'js/main.js' %}"></script>
</html>

blog/blog_app/templates/page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Old+Uyghur&family=Oswald:wght@200&display=swap" rel="stylesheet">
	<link rel="icon" type="image/x-icon" href="{% static 'img/monkey.ico' %}">
	<link rel="stylesheet" href="{% static 'styles/page.css' %}">
</head>
<body>
		<form id="go-back-form" action="{% url 'blog_app:index' %}">
				{%csrf_token%}
				<button>Go back</button>
		</form>

		<div id="container">
				<form action="{% url 'blog_app:update_page' %}" method="POST">
						{%csrf_token%}
						<input type="hidden" value={{page.id}} name="page_id" />
						<label>Title:</label>
						<input type="text" name="title" value="{{page.title}}" />
						<label>Content:</label>
						<textarea name="content">{{page.content}}</textarea>
						<button>Save</button>
				</form>
		</div>			
</body>
</html>