tier_list_project/tier_list/urls.py
from django.urls import path
from . import views

app_name = 'tier_list'

urlpatterns = [
    path('', views.indexView.as_view(), name='index'),
    path('/add/', views.addNewPage, name='add'),
]

tier_list_project/tier_list_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tier_list/', include('tier_list.urls'))
]

tier_list_project/tier_list/models.py
from django.db import models

# Create your models here.

class Departments(models.Model):

    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    img = models.CharField(max_length=200)
    price = models.IntegerField(5)
    location = models.IntegerField(5)

    def __str__(self):
        return self.title

tier_list_project/tier_list/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Departments

# Create your views here.

class indexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'departments'

    def get_queryset(self):
        return Departments.objects.all()

class detailView(generic.DetailView):
    template_name = 'detail.html'
    # model = model

def addNewPage(request):
    rq = request.POST
    dp = Departments(title=rq['title'], link=rq['link'], img=rq['img'], price=rq['price'], location=rq['location'])
    dp.save()
    return HttpResponseRedirect(reverse('tier_list:index'))

tier_list_project/tier_list/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Index</title>
</head>
<body>
				<h1>Departments:</h1><br>

				<h2>Add new department</h2>
				<form action="{% url 'tier_list:add' %}" method="POST">
								{% csrf_token %}
								<label for="title">Title</label>
								<input type="text" id="title" required name="title"><br>

								<label for="link">Link (url)</label>
								<input type="text" id="link" required name="link"><br>

								<label for="img">Img (url)</label>
								<input type="text" name="img" required id="img"><br>

								<label for="price">Price</label>
								<input type="number" max=5 id="price" required name="price"><br>

								<label for="location">Location</label>
								<input type="number" max=5 name="location" required id="location"><br>

								<input type="submit" value="add">
				</form><br>

				<h1>My departments: </h1>
				{% for department in departments %}
				<div style='display: inline-block ;border: 1px solid black; width: 500px; height: 500px; margin: 5px'>
						<p>{{department.title}}</p>
						<p>{{department.img}}</p>
						<p>{{department.price}}</p>
						<p>{{department.location}}</p>
						<p>{{department.link}}</p>
				</div>
				{% endfor %}
</body>
</html>